{% set name = "platformdirs" %}
{% set version = "4.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 357fb2acbc885b0419afd3ce3ed34564c13c9b95c89360cd9563f73aa5e2b907

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.25
    - hatch-vcs >=0.4
  run:
    - python
  run_constrained:
   - mypy>=1.11.2

test:
  source_files:
    - tests
  imports:
    - platformdirs
  commands:
    - pip check
    - pytest tests -vv
  requires:
    - pip
    - pytest
    - pytest-mock
    - appdirs

about:
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    About A small Python module for determining appropriate
    platform-specific dirs, e.g. a "user data dir".
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/

extra:
  recipe-maintainers:
    - adament
    - gaborbernat