{% set name = "platformdirs" %}
{% set version = "3.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f87ca4fcff7d2b0f81c6a748a77973d7af0f4d526f98f308477c3c436c74d528

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling 1.18.0
    - hatch-vcs 0.3.0
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions >=4.6.3  # [py<38]

test:
  source_files:
    - tests
  imports:
    - platformdirs
  commands:
    - pip check
    - pytest tests -vv
  requires:
    - pip
    - pytest
    - pytest-mock
    - appdirs

about:
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  description: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
