{% set name = "platformdirs" %}
{% set version = "2.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/platformdirs-{{ version }}.tar.gz
  sha256: 58c8abb07dcb441e6ee4b11d8df0ac856038f944ab98b7be6b27b2a3c7feef19

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - hatchling >=0.22.0
    - hatch-vcs
  run:
    - python

test:
  imports:
    - platformdirs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/
  doc_source_url: https://github.com/platformdirs/platformdirs/tree/main/docs

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
